version: '3'
services:
  db:
    image: postgres:latest
    container_name: reddit-postgres
    restart: always
    ports:
      - '8080:80'
    environment:
      POSTGRES_USER: '${DB_USER_ID}'
      POSTGRES_PASSWORD: 'DB_USER_PASSWORD'
    volumes:
      - ./data:/var/lib/postgresql/data
